### ISSUE TITLE
Bug with hlx CLI restarts

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative2#186]
Often the hlx CLI needs to be restarted in our local environments when the home page doesn't finish rendering, and gets "stuck". Amol says this seems to be unique to our project and we need to dig in to the cause.

Update: I am seeing this in the console when I try to reload localhost, and then stop it from loading 
```
failed to load module for header TypeError: Failed to fetch
    at fetchFragment (header.js:19:22)
    at header.js:261:35
    at Array.map (<anonymous>)
    at Module.decorate (header.js:255:86)
    at async lib-franklin.js:360:15
    
    Uncaught (in promise) TypeError: Failed to fetch
    at lib-franklin.js:161:9
    at new Promise (<anonymous>)
    at fetchPlaceholders (lib-franklin.js:159:47)
    at delayed.js:3:28
```

**Comment by helms-charity** [comment]
Closing, as I seem to be the only one with this problem.
